language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3.5

install:
  - pip install pymongo
  - pip install pytz

  - pip install pytest

script:
  - python -m pytest
