language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy2
  - pypy3

install:
  - pip install pymongo
  - pip install pytz

  - pip install pytest
  - pip install codecov
  - pip install pytest-cov

script:
  - python -m pytest --cov=codecov
after_success:
  - codecov
